name: dispatch-payload

on: 
  repository_dispatch:
    types: [test,test1]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub event context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo Triggered event text: ${{ toJson(github.event.client_payload) }}