name: shell-test 

on: 
  repository_dispatch:
    types: [test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1  

    - name: Sed Test
      run: |
        echo "$(man sed)"
    
    - name: ECS
      run: aws ecs help
    
    - name: Shell Test1
      run: |
        pwd
        echo '${{ github.workspace }}'

    - name: Shell Test2
      run: | 
        ls -al
        ls -al ../
      working-directory: ./config

    - name: Test array
      env: 
        FRUITS: apple mango melon
      run: |
        env
        echo $FRUITS

    - name: Python
      shell: python
      run: |
        import jinja2
        
        print(dir(jinja2))
